export enum Routes {
    Main = "/",
    Predictor = "/predictor",
    Login = "/login",
    SignUp = "/signup",
    Dashboard = "/dashboard",
    Book = "/book-an-appointment",
    AITool = "/ai-tool",
    History = "/history",
    About = "about",
    Services = "services",
    Team = "/team",
    Faq = "/faq",
    NotFound = "/404",
}
